### ISSUE TITLE
missing arguments

### ISSUE THREAD

**Issue by williamstark01** [yangtcai/Ensembl-Repeat-Identification#42]
The "--configuration ..." line here needs to be uncommented as we started using the configuration file for training:
https://github.com/yangtcai/Ensembl-Repeat-Identification/blob/d64307d335135a3637440eb7ae25d0814cc56160/submit_cluster_job.py#L72-L75

The `iou_threshold` parameter is missing in the function definition:
https://github.com/yangtcai/Ensembl-Repeat-Identification/blob/d64307d335135a3637440eb7ae25d0814cc56160/train.py#L61-L68
as used here:
https://github.com/yangtcai/Ensembl-Repeat-Identification/blob/d64307d335135a3637440eb7ae25d0814cc56160/train.py#L134-L142

**Comment by williamstark01** [comment]
Alright, no worries until then. This can be a small commit on top of the latest PR.

**Comment by yangtcai** [comment]
I think the latest update has resolved this issue:D

**Comment by williamstark01** [comment]
done in #41
