### ISSUE TITLE
Deal with datasets format 

### ISSUE THREAD

**Issue by yangtcai** [yangtcai/Ensembl-Repeat-Identification#5]
Hi, @williamstark01, as our datasets have been generated, the format of the dataset looks like the following
```
sequence format: chr1: 1 - 100000
label format: chr1 start end subtype
```
However, it is not well suited for data loader, as labels don't match sequence, so I plan to change the datasets formats, the new format can be 
```
sequence format: chr1: 1 - 100000
label format: chr1:1-100000 start end subtype
```
What do you think about that?

**Comment by williamstark01** [comment]
Handled in #17
